config/routes.rb
Rails.application.routes.draw do

  get 'favorites/index'
  get 'favorites/update'
  resources :books
  devise_for :users
  root to: 'books#index'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, :author, presence: true

  has_one_attached :cover
  has_many :assignments
  has_many :users, :through => :assignments

  include PgSearch
  pg_search_scope :search_by_title_and_body, :against => [:title, :author],
    using: {
      :tsearch => {:prefix => true}
    }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :first_name, :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites
  has_many :books, through: :assignments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def favorite_text
    return @favorite_exists ? "unfavorite" : "Favorite"
  end

  helper_method :favorite_text

    protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if params[:search]
      @search_results_books = Book.search_by_title_and_body(params[:search])
        respond_to do |format|
          format.js { render partial: 'search-results'}
        end
    else
      @books = Book.paginate(:page => params[:page], :per_page=>10)
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @favorite_exists = Favorite.where(book: @book, user: current_user) == [] ? false : true
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :summary, :rating, :search, :cover)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index

  end

  def update
      favorite = Favorite.where(book: Book.find(params[:book]), user: current_user)
      if favorite == []
        #Create favorite
        Favorite.create(book: Book.find(params[:book]), user: current_user)
        @favorite_exists = true
      else
        #Delete favorite
        favorite.destroy_all
        @favorite_exists = false
      end
      respond_to do |format|
        format.html {}
        format.js {}
    end
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<body class="book-form-background">
  <div class="wrapper book-form">

        <%= form_with(model: book, local: true) do |form| %>
          <% if book.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

              <ul>
                <% book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= form.label :title, class: "book-field-label" %><br>
          <%= form.text_field :title, class: "book-field" %><br>


          <%= form.label :author, class: "book-field-label" %><br>
          <%= form.text_field :author, class: "book-field" %><br>


          <%= form.label :summary, class: "book-field-label" %><br>
          <%= form.text_area :summary, class: "book-field" %><br>

          <%= form.label :rating, class: "book-field-label" %><br>
          <%= form.number_field :rating, class: "book-field" %><br>


          <%- form.label :cover %>
          <%= form.file_field :cover %>
          <br>
          <br>

          <%= form.submit class: "btn btn-success" %>

        <% end %>

    <br>
    
    <br>
    <%= link_to 'Back', books_path, class: "btn btn-secondary" %>
  </div>

</body>

app/views/books/_results.html.erb
<div class="book-grid">
  <% @search_results_books.each do |book| %>
  <div class="card">
    <div class="card-image">
      <figure class="">
        <%= image_tag (book.cover), :size => '238x335' %>
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title">
            <%= book.title %>
          </p>
          <p class="book-text">
            <%= book.author %>
            <%= link_to 'Edit', edit_book_path(book), class: "a-primary"  %>
          </p>
        </div>

      </div>

    </div>
  </div>
  <% end %>

</div>

app/views/books/_search-results.js.erb
$(".book-grid").hide();
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/books/edit.html.erb
<h1 class="edit-label">Edit Book</h1>

<%= render 'form', book: @book %>
<%= link_to 'Delete', book_path(book: @book), data: {:confirm => 'Are you sure?'},:method => :delete , class: "btn btn-danger wrapper book-form" %>

app/views/books/index.html.erb
<body class="index">
  <script src="https://kit.fontawesome.com/42a72c5cd7.js" crossorigin="anonymous"></script>

  <h1 id="index-heading">Books</h1>

  <div class="new-book float-right" style="margin-right: 150px; margin-top: 27px;">
    <%= link_to 'Add Book', new_book_path, class: "btn btn-danger" %>
  </div>

  <div class="search-section">

    <!-- Search -->
      <%= form_tag(books_path, method: :get, remote: true) do %>
        <%= text_field_tag(:search, params[:search], placeholder: "Enter search...", class: "text-field") %>
        <%= submit_tag ("Search"), class: "submit btn-sm" %>
      <% end %>


  </div>
      <div class="book-grid">
        <% @books.each do |book| %>
        <div class="card rounded">
          <div class="card-image">
            <figure class="">
              <%= image_tag (book.cover), :size => '238x335', class: "book-cover" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content" style="margin-left: 10px;">
                <p class="title">
                  <%= book.title %>
                </p>
                <p class="book-text">
                  <%= book.author %>
                </p>

                <%= link_to '', edit_book_path(book), class: "far fa-edit", style: "color: black;" %>
                <%= link_to '', book_path(book.id), class: "far fa-eye", style: "color: black;"%>

              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>



    <div id="search-results">

    </div>
    <%= will_paginate @users , :style=> "margin-left: 100px; margin-top: 30px;"%>


</body>

app/views/books/new.html.erb
<%= render 'form', book: @book%>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @book.summary %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @book.rating %>
</p>

<p>
  <strong>Rating:</strong>
    <%= image_tag @book.cover, :size => '260x260' %>
</p>

<%= link_to favorite_text, favorites_update_path(book: @book), id:'favorite_link', remote: true %>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/favorites/index.html.erb
<body class="favorites">
  <div class="book-grid">
    <% current_user.favorites.each do |favorite| %>
    <div class="card">
      <div class="card-image">
        <figure class="">
          <%= image_tag (favorite.book.cover), :size => '238x335', class: "book-cover"  %>
        </figure>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title">
              <%= favorite.book.title %>
            </p>
            <p class="book-text">
              <%= favorite.book.author %>
            </p>
          </div>

        </div>

      </div>
    </div>
    <% end %>

  </div>
</body>

app/views/favorites/update.js.erb
$('#favorite_link').text("<%= favorite_text %>");

app/views/home/index.html.erb
<!-- Welcome -->

  <div class="about">
    <br>
    <br>
    <p id="welcome-text">Welcome to Bookshelf!</p>
    <br>
    <br>
    <p style="font-size: 25px; color: white;">A community for readers.</p>
  </div>

  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if notice %>
      <p class="alert alert-success" data-dismiss="alert"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbar-Nav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/books/">Books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/favorites/index/">Favorites</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/review/">Review</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/edit/">Account</a>
          </li>
          <li class="nav-link" style="margin-left: 700px; margin-right: 15px; color: black;">
            Hello, <strong><%= current_user.first_name %></strong>
          </li>
          <li class="nav-link">
            <strong><%= link_to 'Logout', destroy_user_session_path, method: :delete, id: "logout-button" %></strong>
          </li>
        </ul>
      </div>
    </nav>

    <% else %>

    <% end %>


    <%= yield %>

  </body>
</html>